# Copyright 2025 Yunze Xu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  release-osx-arm64:
    name: Build binary on macOS arm64
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: build
        run: |
          echo "Building for macOS..."
          mkdir -p build
          cmake -B build
          cmake --build build
          cp ./build/snctl-cpp .

      - name: upload
        uses: actions/upload-artifact@master
        with:
          name: snctl-cpp-macos-14-arm64
          path: |
            snctl-cpp
            sncloud.ini
            install.sh
